"""User chatId dropped

Revision ID: 09f887f3ca1b
Revises: f7fd19c87291
Create Date: 2024-03-11 16:38:03.327025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f887f3ca1b'
down_revision: Union[str, None] = 'f7fd19c87291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegramChatId')
    op.drop_column('users', 'contactInformation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contactInformation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('telegramChatId', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
