"""Add UserState  state field

Revision ID: 421e590b7e0b
Revises: 7f8bf3b9eca2
Create Date: 2024-03-05 23:39:50.369852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421e590b7e0b'
down_revision: Union[str, None] = '7f8bf3b9eca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userStates', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userStates', 'state')
    # ### end Alembic commands ###
