"""Added paymentInfos table

Revision ID: 64ef484bb24e
Revises: e363f63d51a2
Create Date: 2024-10-22 21:51:58.324450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ef484bb24e'
down_revision: Union[str, None] = 'e363f63d51a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentInfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('additionalInfo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymentInfos_id'), 'paymentInfos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paymentInfos_id'), table_name='paymentInfos')
    op.drop_table('paymentInfos')
    # ### end Alembic commands ###
