"""ticket contact information added

Revision ID: 71cccc3faa16
Revises: 24943af64e60
Create Date: 2024-03-12 12:31:12.010693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71cccc3faa16'
down_revision: Union[str, None] = '24943af64e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeTickets', sa.Column('contactInformation', sa.String(), nullable=True))
    op.add_column('imageTickets', sa.Column('contactInformation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imageTickets', 'contactInformation')
    op.drop_column('codeTickets', 'contactInformation')
    # ### end Alembic commands ###
