"""Added ticket.confirmationType

Revision ID: 9324085c81e6
Revises: bc672297b91e
Create Date: 2024-03-26 22:33:38.604414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9324085c81e6'
down_revision: Union[str, None] = 'bc672297b91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeTickets', sa.Column('confirmationType', sa.String(), nullable=True))
    op.add_column('imageTickets', sa.Column('confirmationType', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imageTickets', 'confirmationType')
    op.drop_column('codeTickets', 'confirmationType')
    # ### end Alembic commands ###
