"""Added events.showunti

Revision ID: bc672297b91e
Revises: 30ab92ae4e35
Create Date: 2024-03-26 15:17:23.119315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc672297b91e'
down_revision: Union[str, None] = '30ab92ae4e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('displayUntil', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'displayUntil')
    # ### end Alembic commands ###
