"""user.contact info column added

Revision ID: bf2941f77550
Revises: 86c4ccbadcf9
Create Date: 2024-03-07 19:16:14.641700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2941f77550'
down_revision: Union[str, None] = '86c4ccbadcf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contactInformation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contactInformation')
    # ### end Alembic commands ###
