"""ticket confirmationfileName column added

Revision ID: d9ad251bbc08
Revises: 686914c769c2
Create Date: 2024-03-11 17:38:41.054240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ad251bbc08'
down_revision: Union[str, None] = '686914c769c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeTickets', sa.Column('confirmationFileName', sa.String(), nullable=True))
    op.add_column('imageTickets', sa.Column('confirmationFileName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imageTickets', 'confirmationFileName')
    op.drop_column('codeTickets', 'confirmationFileName')
    # ### end Alembic commands ###
