"""Added hide column for eventGroups

Revision ID: e363f63d51a2
Revises: 2e021c79ecb9
Create Date: 2024-05-27 10:47:31.508604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e363f63d51a2'
down_revision: Union[str, None] = '2e021c79ecb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventGroups', sa.Column('hide', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventGroups', 'hide')
    # ### end Alembic commands ###
