"""Add a column tickets.code

Revision ID: fc7ae8d8af3f
Revises: 29ec597c6f78
Create Date: 2024-03-05 18:13:05.271459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7ae8d8af3f'
down_revision: Union[str, None] = '29ec597c6f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'code')
    # ### end Alembic commands ###
