version: "3.9"
services:
  postgres:
    container_name: postgres_container # композ базы данных создан по этой инструкции https://habr.com/ru/articles/578744/
    image: postgres:15.6
    environment:
      POSTGRES_DB: "paymentBotTest"
      POSTGRES_USER: "paymentBotTest"
      POSTGRES_PASSWORD: "paymentBotTest"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - payment-bot-test-initDb:/docker-entrypoint-initdb.d #скрипты, выполняемые при запуске бд
      - payment-bot-test-data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paymentBotTest -d paymentBotTest"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres
      
  pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4:7.2
      environment:
        PGADMIN_DEFAULT_EMAIL: "habrpguser@habr.com"
        PGADMIN_DEFAULT_PASSWORD: "pgAdmin"
        PGADMIN_CONFIG_SERVER_MODE: "False"
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      ports:
        - "5050:80"
      restart: unless-stopped
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 1G
      networks:
        - postgres

volumes:
  payment-bot-test-data:
  payment-bot-test-initDb:
  pgadmin-data:

networks:
  postgres:
    driver: bridge