"""Added paymentInfo relation for eventGroup

Revision ID: 2b66bd1618e8
Revises: 64ef484bb24e
Create Date: 2024-10-24 10:22:21.258041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b66bd1618e8'
down_revision: Union[str, None] = '64ef484bb24e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventGroups', sa.Column('paymentInfo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'eventGroups', 'paymentInfos', ['paymentInfo_id'], ['id'])
    op.drop_column('events', 'paymentInfo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('paymentInfo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'eventGroups', type_='foreignkey')
    op.drop_column('eventGroups', 'paymentInfo_id')
    # ### end Alembic commands ###
