"""Added event archive 

Revision ID: 34db35491042
Revises: 87a3c05f08cb
Create Date: 2025-01-27 14:55:40.935338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34db35491042'
down_revision: Union[str, None] = '87a3c05f08cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('isArchived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'isArchived')
    # ### end Alembic commands ###
