"""ticket inheritance

Revision ID: 6269f17b5689
Revises: a16f1b1a42b1
Create Date: 2024-03-07 11:16:40.623496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6269f17b5689'
down_revision: Union[str, None] = 'a16f1b1a42b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codeTickets',
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticketId', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imageTickets',
    sa.Column('ticketFilePath', sa.String(), nullable=True),
    sa.Column('telegramFileId', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticketId', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tickets')
    op.add_column('events', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'cost')
    op.create_table('tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ticketId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ticketFilePath', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telegramFileId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='tickets_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tickets_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tickets_pkey')
    )
    op.drop_table('imageTickets')
    op.drop_table('codeTickets')
    # ### end Alembic commands ###
