"""Add UserState added group

Revision ID: 66e79b7c21a0
Revises: bcb03d2c7ba9
Create Date: 2024-03-06 11:43:41.354258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e79b7c21a0'
down_revision: Union[str, None] = 'bcb03d2c7ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userStates', sa.Column('group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userStates', 'group')
    # ### end Alembic commands ###
