"""update log

Revision ID: dbaf8494d15d
Revises: b7a5591b6ab5
Create Date: 2024-03-11 18:36:48.695777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbaf8494d15d'
down_revision: Union[str, None] = 'b7a5591b6ab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UpdateLogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logTimeStamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('telegramTimeStamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('update_type', sa.String(), nullable=True),
    sa.Column('exceptionMessage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UpdateLogs_id'), 'UpdateLogs', ['id'], unique=False)
    op.drop_index('ix_logs_id', table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timeStamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('who', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='logs_pkey')
    )
    op.create_index('ix_logs_id', 'logs', ['id'], unique=False)
    op.drop_index(op.f('ix_UpdateLogs_id'), table_name='UpdateLogs')
    op.drop_table('UpdateLogs')
    # ### end Alembic commands ###
