"""Ticket groupId field added

Revision ID: e875fabc1a24
Revises: 0fafb9ed4d46
Create Date: 2024-03-07 14:04:11.728951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e875fabc1a24'
down_revision: Union[str, None] = '0fafb9ed4d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('groupId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'groupId')
    # ### end Alembic commands ###
